# Generated by Django 6.1.1 on 2026-09-29 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in roles cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Auto-generated ID like EMP-0001.', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('Inventory', 'Inventory'), ('Accounts', 'Accounts'), ('Administration', 'Administration'), ('Operations', 'Operations'), ('Customer Service', 'Customer Service'), ('Other', 'Other')], default='Sales', max_length=50)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('On Leave', 'On Leave')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches this employee can access. Leave empty for all.', related_name='employees', to='team.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user account for this employee.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='team.role')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('team', 'Team'), ('customers', 'Customers'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('custom_orders', 'Custom Orders'), ('reports', 'Reports'), ('metal_prices', 'Metal Prices'), ('settings', 'Settings')], max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='team.employee')),
            ],
            options={
                'ordering': ['module'],
                'unique_together': {('employee', 'module')},
            },
        ),
    ]
