# Generated by Django 6.1.1 on 2026-09-29 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_seed_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate),
        ),
    ]
