# Generated by Django 6.1.1 on 2026-10-01 11:25

import django.db.models.deletion
import team.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_employee_joining_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title or designation, e.g. Senior Gemologist, Sales Head', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, help_text='Profile photo (PNG/JPG/WEBP).', null=True, upload_to='employees/', validators=[team.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user account for this employee (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_proof', 'Identity Proof (Govt ID / Passport / PAN)'), ('contract', 'Employment Contract / Agreement'), ('resume', 'Resume / CV'), ('certificate', 'Certificate / Qualification'), ('other', 'Other Document')], default='other', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='employee_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='team.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_docs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
