# Generated by Django 6.1.1 on 2026-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_seed_hr_support_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('team', 'Team'), ('customers', 'Customers'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('custom_orders', 'Custom Orders'), ('reports', 'Reports'), ('metal_prices', 'Metal Prices'), ('settings', 'Settings'), ('karigar', 'Karigar / Manufacturing')], max_length=30),
        ),
    ]
