# Generated by Django 6.1.1 on 2026-09-22 08:58

import custom_orders.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_jewelleryitem_design_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, help_text='Auto-generated reference, e.g. CO-2026-0001.', max_length=20, unique=True)),
                ('design_description', models.TextField(help_text='What the customer wants made.')),
                ('reference_image', models.FileField(blank=True, help_text='Reference photo/design brought by the customer (JPG, PNG, GIF or PDF).', null=True, upload_to='custom_orders/references/%Y/%m/')),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], max_length=20)),
                ('purity', models.CharField(help_text='e.g. 22K, 18K, 925 Silver', max_length=50)),
                ('approx_gross_weight', models.DecimalField(decimal_places=3, help_text='Approximate weight in grams', max_digits=10)),
                ('approx_net_weight', models.DecimalField(decimal_places=3, help_text='Approximate weight in grams (excluding stones)', max_digits=10)),
                ('making_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated making charge in ₹', max_digits=10)),
                ('estimated_price', models.DecimalField(decimal_places=2, help_text='Estimated total price in ₹', max_digits=12)),
                ('customer_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Customer budget in ₹ (optional)', max_digits=12, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance received in ₹', max_digits=12)),
                ('expected_delivery_date', models.DateField(default=custom_orders.models.default_expected_delivery_date)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Estimate', 'Estimate'), ('Confirmed', 'Confirmed'), ('In Making', 'In Making'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Enquiry', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_orders', to='inventory.category', verbose_name='Jewellery type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
