# Generated by Django 6.1.1 on 2026-09-22 17:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.FileField(blank=True, help_text='Logo image (png/jpg/jpeg/webp/svg). Shown on invoices and in the sidebar (optional).', null=True, upload_to='company/', validators=[accounts.models.validate_logo_extension])),
                ('gstin', models.CharField(blank=True, help_text='15-character GSTIN, e.g. 27ABCDE1234F1Z5', max_length=15, validators=[accounts.models.validate_gstin])),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('invoice_footer_note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
