# Generated by Django 6.1.1 on 2026-10-03 06:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_orders', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0007_jewelleryitem_making_charge_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karigar_code', models.CharField(db_index=True, help_text='Unique artisan ID (e.g. KRG-0001)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Artisan / Workshop Name', max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('alternate_contact', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Workshop / residential address')),
                ('specialization', models.CharField(choices=[('Gold Jewellery', 'Gold Jewellery (Plain / Jadau)'), ('Silver Jewellery', 'Silver Jewellery & Utensils'), ('Diamond Setting', 'Diamond & Gemstone Setting'), ('Casting', 'Casting & Die Work'), ('Polishing & Finishing', 'Polishing, Buffing & Rhodium'), ('Repair & Restoration', 'Repair & Size Alteration'), ('Hand Engraving', 'Hand Engraving / Meenakari'), ('Custom Work', 'Custom Designer Pieces'), ('General / All Rounder', 'General All-Round Artisan'), ('Other', 'Other Work')], default='Gold Jewellery', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('pan_or_id', models.CharField(blank=True, help_text='PAN / Aadhaar / Workshop Reg. for compliance', max_length=50)),
                ('bank_details', models.TextField(blank=True, help_text='Bank Account, IFSC, UPI ID for settlements')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karigar',
                'verbose_name_plural': 'Karigars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KarigarWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_number', models.CharField(db_index=True, help_text='Unique assignment reference (e.g. WA-2026-0001)', max_length=30, unique=True)),
                ('work_type', models.CharField(choices=[('New Making', 'New Piece Making'), ('Repair', 'Repair & Restoration'), ('Polishing', 'Polishing & Finishing'), ('Stone Setting', 'Stone / Diamond Setting'), ('Resizing', 'Resizing / Alteration'), ('Casting', 'Casting & Moulding'), ('Custom Work', 'Custom Work (From Design)'), ('Other', 'Other Work')], default='New Making', max_length=40)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned (Job Issued)'), ('In Progress', 'In Progress'), ('Completed', 'Completed (Ready for Inspection)'), ('Received', 'Received & Verified in Stock'), ('Cancelled', 'Cancelled')], default='Assigned', max_length=20)),
                ('description', models.TextField(help_text='Detailed job instructions, dimensions, design requirements')),
                ('reference_image', models.FileField(blank=True, help_text='Design sketch, CAD render, or reference photo', null=True, upload_to='karigar/designs/%Y/%m/')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Other', 'Other')], default='Gold', max_length=20)),
                ('purity', models.CharField(default='22K', help_text='e.g. 24K, 22K (916), 18K (750), 925 Silver', max_length=50)),
                ('gross_weight_issued', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Gross weight of raw gold/scrap issued in grams', max_digits=10)),
                ('stone_weight_issued', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Weight of stones/beads/findings issued', max_digits=10)),
                ('net_weight_issued', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Net precious metal issued (Gross - Stones)', max_digits=10)),
                ('gross_weight_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Finished piece gross weight in grams', max_digits=10)),
                ('stone_weight_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Finished piece stone weight in grams', max_digits=10)),
                ('net_weight_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Finished piece net precious metal weight in grams', max_digits=10)),
                ('scrap_weight_returned', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Cut pieces, filings, or scrap gold returned back by artisan', max_digits=10)),
                ('wastage_allowed_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allowed manufacturing wastage % (e.g. 1.50%)', max_digits=5)),
                ('wastage_weight_allowed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Allowed wastage in grams (Net Issued * Wastage %)', max_digits=10)),
                ('actual_wastage_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Actual loss = Net Issued - (Net Received + Scrap Returned)', max_digits=10)),
                ('weight_difference', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Actual Wastage - Allowed Wastage (+ve = excess loss, -ve = recovery gain)', max_digits=10)),
                ('making_charge_type', models.CharField(choices=[('Fixed Amount', 'Fixed Amount (₹)'), ('Per Gram', 'Per Gram (₹/g)'), ('Percentage', 'Percentage of Metal Value (%)')], default='Per Gram', max_length=20)),
                ('making_charge_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate in ₹ (e.g. ₹450/g or fixed ₹2,500)', max_digits=10)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated making charge in ₹', max_digits=12)),
                ('stone_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stone setting / diamond charges in ₹', max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rhodium, hallmarking, casting or polish charges in ₹', max_digits=12)),
                ('other_charges_description', models.CharField(blank=True, help_text='Description of other approved charges', max_length=200)),
                ('total_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total artisan charge (Labour + Stones + Others)', max_digits=12)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_assignments_issued', to=settings.AUTH_USER_MODEL)),
                ('custom_order', models.ForeignKey(blank=True, help_text='Linked custom order if assigned for order fulfillment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_assignments', to='custom_orders.customorder')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer if this work is for a customer repair or bespoke piece', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_assignments', to='customers.customer')),
                ('inventory_item', models.ForeignKey(blank=True, help_text='Existing inventory piece issued for repair, polishing, or resizing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_assignments', to='inventory.jewelleryitem')),
                ('karigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='karigar.karigar')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('stock_movement_issued', models.ForeignKey(blank=True, help_text='Audit record when showroom item was issued to Karigar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_issue_assignments', to='inventory.stockmovement')),
                ('stock_movement_received', models.ForeignKey(blank=True, help_text='Audit record when finished piece was received into inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karigar_receipt_assignments', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'Work Assignment',
                'verbose_name_plural': 'Work Assignments',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KarigarSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(db_index=True, help_text='Unique settlement reference (e.g. KST-2026-0001)', max_length=30, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in ₹', max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI Payment'), ('Cheque', 'Cheque')], default='Cash', max_length=30)),
                ('payment_reference', models.CharField(blank=True, help_text='Cheque # / UTR / Transaction reference', max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_karigar_settlements', to=settings.AUTH_USER_MODEL)),
                ('karigar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='karigar.karigar')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_karigar_settlements', to=settings.AUTH_USER_MODEL)),
                ('assignments', models.ManyToManyField(blank=True, help_text='Work assignments settled by this payment', related_name='settlements', to='karigar.karigarworkassignment')),
            ],
            options={
                'verbose_name': 'Karigar Settlement',
                'verbose_name_plural': 'Karigar Settlements',
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
