# Generated by Django 6.1.1 on 2026-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karigar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karigarworkassignment',
            name='purity',
            field=models.CharField(blank=True, default='22K', help_text='e.g. 24K, 22K (916), 18K (750), 925 Silver', max_length=50),
        ),
    ]
