# Generated by Django 6.1.1 on 2026-09-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JewelleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], max_length=20)),
                ('purity', models.CharField(help_text='e.g. 22K, 18K, 925 Silver, VVS-1', max_length=50)),
                ('gross_weight', models.DecimalField(decimal_places=3, help_text='Weight in grams', max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, help_text='Weight in grams (excluding stones/wax)', max_digits=10)),
                ('making_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
