# Generated by Django 6.1.1 on 2026-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='design_code',
            field=models.CharField(blank=True, db_index=True, help_text='Design / Model Code (e.g. DSN-GLD-001). Multiple physical pieces can share the same design code.', max_length=50),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='item_code',
            field=models.CharField(help_text='Unique piece ID / Tag / Barcode', max_length=50, unique=True),
        ),
    ]
