# Generated by Django 6.1.1 on 2026-09-26 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_jewelleryitem_design_code_and_more'),
        ('sales', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Pieces of this item currently held in stock.'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Addition', 'Stock Addition'), ('Reduction', 'Stock Reduction'), ('Adjustment', 'Stock Adjustment'), ('Sale', 'Sale')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Signed piece change: positive adds stock, negative removes it.')),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, choices=[('New Stock Received', 'New Stock Received'), ('Returned by Customer', 'Returned by Customer'), ('Damaged Item', 'Damaged Item'), ('Lost Item', 'Lost Item'), ('Stock Correction', 'Stock Correction'), ('Manual Adjustment', 'Manual Adjustment'), ('Sale', 'Sale')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.jewelleryitem')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='stock_movement_change_not_zero'), models.CheckConstraint(condition=models.Q(('stock_after__gte', 0)), name='stock_movement_after_not_negative')],
            },
        ),
    ]
