# Generated by Django 6.1.1 on 2026-09-27 09:57

from decimal import Decimal
from django.db import migrations, models


def populate_existing_jewellery_tags(apps, schema_editor):
    JewelleryItem = apps.get_model('inventory', 'JewelleryItem')
    ItemSequence = apps.get_model('inventory', 'ItemSequence')

    counter = 0
    # Process items ordered by id so earlier created pieces get smaller tag numbers
    for item in JewelleryItem.objects.order_by('id'):
        counter += 1
        item.tag_number = f"JWL-{counter:06d}"
        if not item.stone_weight:
            item.stone_weight = Decimal('0.000')
        item.save(update_fields=['tag_number', 'stone_weight'])

    ItemSequence.objects.update_or_create(
        name='jewellery_tag',
        defaults={'last_number': counter}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_jewelleryitem_quantity_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='jewellery_tag', max_length=50, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item Sequence',
                'verbose_name_plural': 'Item Sequences',
            },
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='hallmark_details',
            field=models.CharField(blank=True, help_text='Hallmark center / assaying notes or certification details', max_length=150),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='hallmark_status',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Hallmarked', 'Hallmarked')], default='Not Applicable', help_text='Hallmark status', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='huid',
            field=models.CharField(blank=True, db_index=True, help_text='6-character alphanumeric BIS Hallmarking Unique ID (Indian jewellery inventory)', max_length=6),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='huid_status',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Pending', 'Pending'), ('Verified', 'Verified')], default='Not Applicable', help_text='HUID authentication status', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='stone_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stone / bead / wax weight in grams', max_digits=10),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='tag_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique physical jewellery piece tag number (e.g. JWL-000001)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, help_text='Gross weight in grams', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net precious metal weight in grams (gross weight minus stone weight)', max_digits=10),
        ),
        migrations.RunPython(populate_existing_jewellery_tags, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='tag_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique physical jewellery piece tag number (e.g. JWL-000001)', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
