# Generated by Django 6.1.1 on 2026-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_jewellery_identity_authentication'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jewelleryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('huid', ''), _negated=True), fields=('huid',), name='unique_nonblank_huid'),
        ),
    ]
