# Generated by Django 6.1.1 on 2026-09-27 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_jewellery_huid_unique_when_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelleryitem',
            name='metal_type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net precious metal weight in grams (gross weight minus stone weight; auto = gross - stone)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='stone_weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Stone / bead / wax weight in grams', max_digits=10),
        ),
    ]
