# Generated by Django 6.1.1 on 2026-10-01 17:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_jewelleryitem_metal_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelleryitem',
            name='making_charge_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount (₹)'), ('Per Gram', 'Per Gram (₹/g)'), ('Percentage', 'Percentage (%)')], default='Fixed Amount', help_text='How making charges are calculated (Fixed ₹, Per gram, or %)', max_length=20),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='other_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Hallmarking, certification or other charges in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='stone_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Stone / diamond / bead charges in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='wastage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Manufacturing wastage percentage (e.g. 3.00%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platinum')], max_length=20, unique=True)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, help_text='Standard rate per gram in INR (24K for Gold, 999 for Silver, 950 for Platinum)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='Manual', help_text='Rate source (e.g. Manual, Live API, IBJA)', max_length=50)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_metal_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metal Rate',
                'verbose_name_plural': 'Metal Rates',
                'ordering': ['metal_type'],
            },
        ),
    ]
