"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ttj_u4t9h1q#5nt-5j%p60fjv(+#ke1o_@*k$g!1)#$imf@t_v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'accounts',
    'inventory',
    'customers',
    'sales',
    'custom_orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.company_settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Uploaded files (e.g. custom order reference photos).
# Served by Django itself only while DEBUG is True (development).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
# Inventory ------------------------------------------------------------------
#
# Low-stock threshold, in pieces. A design (all physical pieces sharing a
# design code) that still has stock but is down to this many pieces or fewer is
# flagged as "Low Stock" on the inventory pages. The inventory list also
# accepts a per-request override via ?threshold=. Default: 1 piece (the last
# piece of a design). Set the environment variable
# JEWELDESK_LOW_STOCK_THRESHOLD to change it without touching the code.

INVENTORY_LOW_STOCK_THRESHOLD = int(
    os.environ.get('JEWELDESK_LOW_STOCK_THRESHOLD', '1'))


# Metal prices (dashboard) ---------------------------------------------------

#
# Gold (XAU) / Silver (XAG) rates shown on the dashboard come from an
# external API. Credentials are read from environment variables only — never
# hard-code a key in this file. On Windows set for example:
#     setx JEWELDESK_METAL_PRICE_API_KEY "your-key-here"
# The URL may contain an ``{api_key}`` placeholder which is substituted from
# METAL_PRICE_API_KEY when the request is made.

METAL_PRICE_API_URL = os.environ.get(
    'JEWELDESK_METAL_PRICE_API_URL',
    'https://api.metalpriceapi.com/v1/latest?api_key={api_key}&base=INR&currencies=XAU,XAG',
)
METAL_PRICE_API_KEY = os.environ.get('JEWELDESK_METAL_PRICE_API_KEY', '')
METAL_PRICE_API_KEY_HEADER = os.environ.get(
    'JEWELDESK_METAL_PRICE_API_KEY_HEADER', 'x-access-token')
METAL_PRICE_API_TIMEOUT = int(os.environ.get('JEWELDESK_METAL_PRICE_API_TIMEOUT', '5'))
METAL_PRICE_CACHE_TTL = int(os.environ.get('JEWELDESK_METAL_PRICE_CACHE_TTL', '1800'))
