"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    os.environ.get('SECRET_KEY', 'django-insecure-ttj_u4t9h1q#5nt-5j%p60fjv(+#ke1o_@*k$g!1)#$imf@t_v')
)

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically set to False on Vercel deployment unless explicitly overridden via DJANGO_DEBUG=True.
# In local development (where VERCEL is not set), it defaults to True for convenience.
DEBUG = os.environ.get(
    'DJANGO_DEBUG',
    os.environ.get('DEBUG', 'False' if os.environ.get('VERCEL') else 'True')
).lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    'jwel-desk.vercel.app',
    '.vercel.app',
    'localhost',
    '127.0.0.1',
    '[::1]',
    'testserver',
]

# Allow custom hosts from environment variables if defined
extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if extra_hosts:
    ALLOWED_HOSTS.extend([h.strip() for h in extra_hosts.split(',') if h.strip()])

# If VERCEL_URL is injected by Vercel environment (e.g. jwel-desk-xxx.vercel.app)
vercel_url = os.environ.get('VERCEL_URL')
if vercel_url and vercel_url not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(vercel_url)

CSRF_TRUSTED_ORIGINS = [
    'https://jwel-desk.vercel.app',
    'https://*.vercel.app',
    # Local development origins – required by Django 4.0+ when the browser
    # sends an Origin or Referer header with HTTP requests.
    'http://localhost',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
]

extra_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in extra_csrf.split(',') if origin.strip()])

if vercel_url:
    origin = f"https://{vercel_url}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Reverse proxy SSL header for Vercel edge CDN
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Silenced system checks
SILENCED_SYSTEM_CHECKS = [
    'mail.E001',
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'accounts',
    'inventory',
    'customers',
    'sales',
    'custom_orders',
    'team',
    'karigar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.company_settings_context',
                'team.context_processors.team_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

default_sqlite_path = BASE_DIR / 'db.sqlite3'

# Production database URL (e.g. Neon, Supabase, Vercel Postgres, Railway)
# Supports DATABASE_URL, POSTGRES_URL, or POSTGRES_PRISMA_URL
_database_url = (
    os.environ.get('DATABASE_URL')
    or os.environ.get('POSTGRES_URL')
    or os.environ.get('POSTGRES_PRISMA_URL')
)

if _database_url:
    # When deployed on Vercel or using Supabase Transaction Pooler (port 6543 / PgBouncer):
    # - conn_max_age default 60s allows warm serverless workers to reuse established TLS/DB
    #   connections without paying a 400-800ms handshake penalty on every request.
    #   conn_health_checks=True safely verifies connection vitality before query execution.
    # - DISABLE_SERVER_SIDE_CURSORS is set to True (PgBouncer in transaction mode does not support PostgreSQL named cursors)
    # - SSL is required for remote database connections
    conn_max_age_val = int(os.environ.get('CONN_MAX_AGE', '60'))
    ssl_required = 'localhost' not in _database_url and '127.0.0.1' not in _database_url

    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(
                _database_url,
                conn_max_age=conn_max_age_val,
                conn_health_checks=True,
                ssl_require=ssl_required,
                disable_server_side_cursors=True,
            )
        }
    except ImportError:
        from urllib.parse import urlparse, unquote
        parsed = urlparse(_database_url)
        engine = 'django.db.backends.postgresql'
        if 'sqlite' in parsed.scheme:
            engine = 'django.db.backends.sqlite3'
        elif 'mysql' in parsed.scheme:
            engine = 'django.db.backends.mysql'

        DATABASES = {
            'default': {
                'ENGINE': engine,
                'NAME': unquote(parsed.path.lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or '',
                'PORT': parsed.port or '',
                'CONN_MAX_AGE': conn_max_age_val,
            }
        }

    # Ensure Supabase Transaction Pooler compatibility:
    # 1. Transaction mode does not support server-side cursors
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

    # 2. Enforce SSL require for remote PostgreSQL hosts
    if ssl_required:
        options = DATABASES['default'].setdefault('OPTIONS', {})
        options.setdefault('sslmode', 'require')

elif os.environ.get('VERCEL'):
    # Ephemeral fallback for Vercel if DATABASE_URL is not yet configured.
    # Note: A hosted PostgreSQL (Supabase/Neon) DATABASE_URL
    # must be provided for persistent data across serverless invocations.
    default_db_path = Path('/tmp') / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': default_db_path,
        }
    }
else:
    # Local development: persist to local SQLite database file (existing data intact)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': default_sqlite_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Cache headers for static assets: 1 day on production/Vercel CDN, 0 in local development
WHITENOISE_MAX_AGE = int(os.environ.get('WHITENOISE_MAX_AGE', '86400' if not DEBUG else '0'))

# In-memory cache for process-level caching of singletons, metal prices & query results
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'jeweldesk-locmem',
    }
}

# Uploaded files (e.g. custom order reference photos).
# Served by Django itself only while DEBUG is True (development).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Email Configuration
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# By default, emails are written to the console during local development and testing
# when SMTP environment variables are not set.
# For production email delivery, set the following environment variables:
#   EMAIL_HOST            - SMTP host (e.g., smtp.sendgrid.net, smtp.gmail.com)
#   EMAIL_PORT            - SMTP port (e.g., 587 for TLS, 465 for SSL, default: 587)
#   EMAIL_HOST_USER       - SMTP username / API key identity
#   EMAIL_HOST_PASSWORD   - SMTP password / API secret key
#   EMAIL_USE_TLS         - True/False (default: True when port != 465)
#   EMAIL_USE_SSL         - True/False (default: True when port == 465)
#   DEFAULT_FROM_EMAIL    - Sender email address (e.g., 'JewelDesk <no-reply@jeweldesk.com>')
#   EMAIL_BACKEND         - Optional override for custom email backend

_email_host = os.environ.get('EMAIL_HOST', '')
_email_port = int(os.environ.get(
    'EMAIL_PORT',
    '465' if os.environ.get('EMAIL_USE_SSL', '').lower() in ('1', 'true', 'yes') else '587'
))
_email_user = os.environ.get('EMAIL_HOST_USER', '')
_email_password = os.environ.get('EMAIL_HOST_PASSWORD', '')

_use_ssl_env = os.environ.get('EMAIL_USE_SSL')
if _use_ssl_env is not None:
    _email_use_ssl = _use_ssl_env.lower() in ('1', 'true', 'yes')
else:
    _email_use_ssl = (_email_port == 465)

_use_tls_env = os.environ.get('EMAIL_USE_TLS')
if _use_tls_env is not None:
    _email_use_tls = _use_tls_env.lower() in ('1', 'true', 'yes')
else:
    _email_use_tls = not _email_use_ssl

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    os.environ.get('SERVER_EMAIL', 'JewelDesk <no-reply@jeweldesk.com>')
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

_custom_email_backend = os.environ.get('EMAIL_BACKEND')
if _custom_email_backend:
    _active_email_backend = _custom_email_backend
elif _email_host:
    _active_email_backend = 'django.core.mail.backends.smtp.EmailBackend'
else:
    _active_email_backend = 'django.core.mail.backends.console.EmailBackend'

# Django 6.0+ MAILERS configuration
_mailer_options = {}
if _active_email_backend == 'django.core.mail.backends.smtp.EmailBackend':
    _mailer_options = {
        'host': _email_host,
        'port': _email_port,
        'username': _email_user,
        'password': _email_password,
        'use_tls': _email_use_tls,
        'use_ssl': _email_use_ssl,
    }

MAILERS = {
    'default': {
        'BACKEND': _active_email_backend,
        'OPTIONS': _mailer_options,
    },
}

# Password reset token expiry (in seconds, default 3 days = 259200)
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', '259200'))


# Inventory ------------------------------------------------------------------
#
# Low-stock threshold, in pieces. A design (all physical pieces sharing a
# design code) that still has stock but is down to this many pieces or fewer is
# flagged as "Low Stock" on the inventory pages. The inventory list also
# accepts a per-request override via ?threshold=. Default: 1 piece (the last
# piece of a design). Set the environment variable
# JEWELDESK_LOW_STOCK_THRESHOLD to change it without touching the code.

INVENTORY_LOW_STOCK_THRESHOLD = int(
    os.environ.get('JEWELDESK_LOW_STOCK_THRESHOLD', '1'))


# Metal prices (dashboard) ---------------------------------------------------

#
# Gold (XAU) / Silver (XAG) rates shown on the dashboard come from an
# external API. Credentials are read from environment variables only — never
# hard-code a key in this file. On Windows set for example:
#     setx JEWELDESK_METAL_PRICE_API_KEY "your-key-here"
# The URL may contain an ``{api_key}`` placeholder which is substituted from
# METAL_PRICE_API_KEY when the request is made.

METAL_PRICE_API_URL = os.environ.get(
    'JEWELDESK_METAL_PRICE_API_URL',
    'https://api.metalpriceapi.com/v1/latest?api_key={api_key}&base=INR&currencies=XAU,XAG',
)
METAL_PRICE_API_KEY = os.environ.get('JEWELDESK_METAL_PRICE_API_KEY', '')
METAL_PRICE_API_KEY_HEADER = os.environ.get(
    'JEWELDESK_METAL_PRICE_API_KEY_HEADER', 'x-access-token')
METAL_PRICE_API_TIMEOUT = int(os.environ.get('JEWELDESK_METAL_PRICE_API_TIMEOUT', '5'))
METAL_PRICE_CACHE_TTL = int(os.environ.get('JEWELDESK_METAL_PRICE_CACHE_TTL', '1800'))

# Fast password hashing during automated tests
import sys
if 'test' in sys.argv:
    from django.contrib.auth.hashers import PBKDF2PasswordHasher
    PBKDF2PasswordHasher.iterations = 1

# Application Version & PWA Build Info
APP_VERSION = '2.1.0'
APP_BUILD_ID = '20261010-v21'
