# Generated by Django 6.1.1 on 2026-10-03 06:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Exchange', 'Exchange / Old Gold')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Exchange', 'Exchange / Old Gold')], default='Cash', max_length=20),
        ),
        migrations.CreateModel(
            name='OldGoldTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(db_index=True, help_text='Unique voucher reference (e.g. OGX-00001, OGB-00001)', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('Exchange', 'Exchange with New Jewellery'), ('Buyback', 'Outright Buyback (Cash Payout)')], default='Exchange', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metal_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Other', 'Other')], default='Gold', max_length=20)),
                ('old_gold_type', models.CharField(choices=[('Old Jewellery', 'Old Jewellery / Ornaments'), ('Broken Jewellery', 'Broken Jewellery Pieces'), ('Scrap Gold', 'Scrap Gold'), ('Coins / Bullion', 'Gold Coins / Bullion Bar'), ('Silver Scrap', 'Silver Scrap / Utensils'), ('Other', 'Other Scrap Metal')], default='Old Jewellery', max_length=50)),
                ('item_description', models.CharField(help_text='e.g. Broken 22K Bangle, Mangalsutra chain pieces', max_length=255)),
                ('gross_weight', models.DecimalField(decimal_places=3, help_text='Total physical weight in grams', max_digits=10)),
                ('stone_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stone, enamel, wax or non-metal weight in grams', max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, help_text='Net precious metal weight in grams (gross - stone)', max_digits=10)),
                ('purity', models.CharField(choices=[('24K', '24K (99.9% Pure)'), ('22K', '22K / 916 (91.6%)'), ('20K', '20K (83.3%)'), ('18K', '18K / 750 (75.0%)'), ('14K', '14K / 585 (58.5%)'), ('10K', '10K (41.7%)'), ('925', '925 Sterling Silver'), ('Other', 'Other / Custom Purity')], default='22K', max_length=50)),
                ('custom_purity_percent', models.DecimalField(blank=True, decimal_places=2, help_text="Custom purity % if 'Other' selected", max_digits=5, null=True)),
                ('purity_factor', models.DecimalField(decimal_places=6, default=Decimal('0.916667'), help_text='Purity multiplier (e.g. 0.916667 for 22K)', max_digits=8)),
                ('pure_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Equivalent 24K pure metal weight in grams', max_digits=10)),
                ('applicable_rate', models.DecimalField(decimal_places=2, help_text='Standard 24K rate per gram in INR at time of intake', max_digits=12)),
                ('effective_rate', models.DecimalField(decimal_places=2, help_text='Rate per gram for this purity in INR (applicable_rate * purity_factor)', max_digits=12)),
                ('gross_valuation', models.DecimalField(decimal_places=2, help_text='Gross gold value before deductions (net_weight * effective_rate)', max_digits=12)),
                ('deduction_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Melting/testing wastage deduction percentage', max_digits=5)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deduction in INR', max_digits=12)),
                ('final_value', models.DecimalField(decimal_places=2, help_text='Final old gold valuation credited or paid (Gross - Deductions)', max_digits=12)),
                ('inventory_status', models.CharField(choices=[('Vault Stock', 'Scrap in Vault (Not for sale)'), ('Sent for Refining', 'Sent to Refinery / Melter'), ('Melted', 'Melted into Bullion'), ('Refined Bar', 'Refined Bullion Bar Received')], default='Vault Stock', help_text='Kept separate from normal showroom stock', max_length=30)),
                ('new_item_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price of the new jewellery piece', max_digits=12, null=True)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='New Item Price - Old Gold Final Value (+ve = Customer owes, -ve = Refund due)', max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Adjusted in Sale', 'Adjusted in Sale (Exchange)')], default='Cash', max_length=30)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='Paid', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank / UPI reference or cheque number', max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_old_golds', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_gold_transactions', to='customers.customer')),
                ('new_sale', models.OneToOneField(blank=True, help_text='Linked sale when old gold is used towards new jewellery purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_gold_exchange', to='sales.sale')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_old_golds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Old Gold Transaction',
                'verbose_name_plural': 'Old Gold Transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
